import CK
import CKF2.Spec

#print axioms CK.Algebra.q
#print axioms CK.Algebra.variance_restriction
#print axioms CK.Algebra.variance_range
#print axioms CK.Algebra.mixture_left
#print axioms CK.Algebra.mixture_right
#print axioms CK.Algebra.small_gap_pair
#print axioms CK.Algebra.induction_step
#print axioms CK.Algebra.deficit_identity
#print axioms CK.Algebra.bias_payment
#print axioms CK.Algebra.complete_square
#print axioms CK.Algebra.product_transfer_direct
#print axioms CK.Algebra.gain_factorization
#print axioms CK.Algebra.centering_remainder
#print axioms CK.Algebra.centering_sign
#print axioms CK.Algebra.curvature_integrand
#print axioms CK.Algebra.endpoint_polynomial_identity
#print axioms CK.Algebra.endpoint_polynomial_margin
#print axioms CK.Algebra.antipodal_pointwise
#print axioms CK.Algebra.section_bound
#print axioms CK.Algebra.majorant
#print axioms CK.Algebra.majorant_factorization
#print axioms CK.Algebra.majorant_even
#print axioms CK.Algebra.majorant_halfline
#print axioms CK.Algebra.majorant_absolute
#print axioms CK.Algebra.linear_margin_dominates
#print axioms CK.Algebra.weighted_coefficient
#print axioms CK.Algebra.weighted_step
#print axioms CK.atanhLog
#print axioms CK.curvature
#print axioms CK.curvatureGap
#print axioms CK.CurvatureGoal
#print axioms CK.pairEntropy
#print axioms CK.ProductCenteringGoal
#print axioms CK.logPartial
#print axioms CK.logTail
#print axioms CK.LogEnclosureGoal
#print axioms CK.psi
#print axioms CK.lambdaDenom
#print axioms CK.EntropyComparisonGoal
#print axioms CK.StrictAnchorGoal
#print axioms CK.ProbabilityKernelGoal
#print axioms CK.atanhLog_third
#print axioms CK.eta_third
#print axioms CK.anchorD
#print axioms CK.anchorD'
#print axioms CK.hasDerivAt_anchorD
#print axioms CK.hasDerivAt_anchorD'
#print axioms CK.anchorD'_monotoneOn
#print axioms CK.anchorD'_third_neg
#print axioms CK.anchorD_antitoneOn
#print axioms CK.anchorD_third_pos
#print axioms CK.anchor_caseC
#print axioms CK.anchor_caseA
#print axioms CK.strict_anchor
#print axioms CK.avg_add
#print axioms CK.avg_const_mul
#print axioms CK.avg_sub
#print axioms CK.avg_le_avg
#print axioms CK.abs_avg_le_avg_abs
#print axioms CK.avg_of_unique
#print axioms CK.binaryEntropy_nonneg'
#print axioms CK.binaryEntropy_symm
#print axioms CK.conditionalEntropy_nonneg
#print axioms CK.posterior_zero
#print axioms CK.mean_zero
#print axioms CK.binaryEntropy_eq_eta
#print axioms CK.pairEntropy_neg_right
#print axioms CK.pairEntropy_abs_left
#print axioms CK.pairEntropy_mul_abs
#print axioms CK.pairEntropy_abs_right
#print axioms CK.half_sum_entropy_eq
#print axioms CK.mixedEntropy_eq
#print axioms CK.scalarSlack_eq
#print axioms CK.nu_add_t_le_one
#print axioms CK.abs_sub_eq_one_cases
#print axioms CK.scalarSlack_nonneg_of_eq
#print axioms CK.le_binaryEntropy_of_small'
#print axioms CK.scalarSlack_endpoints
#print axioms CK.envelope_of_criterion
#print axioms CK.one_le_lambdaDenom
#print axioms CK.lambdaReq_le_lambdaBar
#print axioms CK.lambdaBar
#print axioms CK.lbNum
#print axioms CK.lbNum_nonneg
#print axioms CK.hasDerivAt_lambdaDenom
#print axioms CK.hasDerivAt_lbNum
#print axioms CK.lambdaBarD1
#print axioms CK.hasDerivAt_lambdaBar
#print axioms CK.lambdaBarD2
#print axioms CK.hasDerivAt_lambdaBarD1
#print axioms CK.D2_numer_nonneg
#print axioms CK.lambdaBarD2_nonneg
#print axioms CK.lambdaBar_convexOn
#print axioms CK.lambdaBar_lt_knot0
#print axioms CK.lambdaBar_lt_knot1
#print axioms CK.lambdaBar_lt_knot2
#print axioms CK.lambdaBar_lt_knot3
#print axioms CK.s_knot0
#print axioms CK.s_knot1
#print axioms CK.s_knot2
#print axioms CK.s_knot3
#print axioms CK.cubic0
#print axioms CK.cubic1
#print axioms CK.cubic2
#print axioms CK.segment_criterion
#print axioms CK.entropy_comparison
#print axioms CK.large_coordinate
#print axioms CK.complementary_proved
#print axioms CK.courtadeKumar_proved
#print axioms CK.AppF.log_q2
#print axioms CK.AppF.log_q3
#print axioms CK.AppF.log_q20
#print axioms CK.AppF.log_q50_3
#print axioms CK.AppF.log_q459_250
#print axioms CK.AppF.log_q59_21
#print axioms CK.AppF.log_q137_23
#print axioms CK.AppF.log_q22_3
#print axioms CK.AppF.log_q899_101
#print axioms CK.AppF.log_q459_41
#print axioms CK.AppF.log_q199_60
#print axioms CK.AppF.log_q127_40
#print axioms CK.AppF.log_q3967_1000
#print axioms CK.AppF.log_q4883_1000
#print axioms CK.AppF.log_q5619_1000
#print axioms CK.AppF.log_q5
#print axioms CK.AppF.log_q8
#print axioms CK.AppF.log_q40_3
#print axioms CK.AppF.log_q4
#print axioms CK.AppF.log_q7
#print axioms CK.AppF.log_q10
#print axioms CK.AppF.log_q9
#print axioms CK.AppF.log_q25
#print axioms CK.AppF.log_q23
#print axioms CK.AppF.log_q50
#print axioms CK.AppF.log_q47
#print axioms CK.AppF.log_q19
#print axioms CK.AppF.row_log_q2_lo
#print axioms CK.AppF.row_log_q2_hi
#print axioms CK.AppF.row_log_q3_lo
#print axioms CK.AppF.row_log_q3_hi
#print axioms CK.AppF.row_log_q20_lo
#print axioms CK.AppF.row_log_q20_hi
#print axioms CK.AppF.row_log_q50_3_lo
#print axioms CK.AppF.row_log_q459_250_lo
#print axioms CK.AppF.row_log_q59_21_lo
#print axioms CK.AppF.row_log_q137_23_lo
#print axioms CK.AppF.row_log_q22_3_lo
#print axioms CK.AppF.row_log_q899_101_lo
#print axioms CK.AppF.row_log_q459_41_hi
#print axioms CK.AppF.row_log_q199_60_lo
#print axioms CK.AppF.row_log_q127_40_lo
#print axioms CK.AppF.row_log_q3967_1000_lo
#print axioms CK.AppF.row_log_q4883_1000_lo
#print axioms CK.AppF.row_log_q5619_1000_lo
#print axioms CK.AppF.knot_rho_3_5
#print axioms CK.AppF.knot_rho_3_4
#print axioms CK.AppF.knot_rho_17_20
#print axioms CK.AppF.knot_rho_9_10
#print axioms CK.AppF.row_h_1_4_lo
#print axioms CK.AppF.row_h_1_8_lo
#print axioms CK.AppF.row_h_1_10_lo
#print axioms CK.AppF.row_h_2_25_lo
#print axioms CK.AppF.row_h_3_50_lo
#print axioms CK.AppF.row_h_1_5_lo
#print axioms CK.AppF.row_h_1_20_hi
#print axioms CK.AppF.comb_log3
#print axioms CK.AppF.comb_log2
#print axioms CK.AppF.comb_rat1
#print axioms CK.AppF.comb_rat2
#print axioms CK.AppF.comb_rat3
#print axioms CK.wAux
#print axioms CK.wAux_zero
#print axioms CK.wAux_one
#print axioms CK.continuous_wAux
#print axioms CK.hasDerivAt_wAux
#print axioms CK.wAux_nonneg
#print axioms CK.psiCurv
#print axioms CK.psiCurvDeriv
#print axioms CK.hasDerivAt_psiCurv
#print axioms CK.psiCurvDeriv_nonneg
#print axioms CK.psiCurv0
#print axioms CK.psiCurv_zero_eq
#print axioms CK.psiCurv0_continuousAt
#print axioms CK.curvature_identity
#print axioms CK.ent
#print axioms CK.IsDist
#print axioms CK.noisy
#print axioms CK.deficit
#print axioms CK.kernel_col_sum
#print axioms CK.sum_noisy
#print axioms CK.noisy_nonneg
#print axioms CK.noisy_isDist
#print axioms CK.noisy_add
#print axioms CK.noisy_smul
#print axioms CK.noisy_sum
#print axioms CK.ent_nonneg
#print axioms CK.ent_mixture_ge
#print axioms CK.deficit_bool
#print axioms CK.ent_bool
#print axioms CK.ent_zero_dim
#print axioms CK.deficit_zero_dim
#print axioms CK.sum_snoc
#print axioms CK.marg
#print axioms CK.condDist
#print axioms CK.marg_nonneg
#print axioms CK.sum_marg
#print axioms CK.snoc_eq_zero_of_marg
#print axioms CK.snoc_eq_marg_mul_condDist
#print axioms CK.condDist_nonneg
#print axioms CK.sum_condDist
#print axioms CK.condDist_isDist
#print axioms CK.marg_mul_sum_condDist
#print axioms CK.sum_condDist_mul_negMulLog
#print axioms CK.ent_chain
#print axioms CK.deficit_chain
#print axioms CK.k1
#print axioms CK.k1_nonneg
#print axioms CK.sum_k1
#print axioms CK.noisy_snoc
#print axioms CK.marg_noisy
#print axioms CK.lam
#print axioms CK.mix
#print axioms CK.lam_nonneg
#print axioms CK.sum_lam
#print axioms CK.lam_mul_sum_condDist
#print axioms CK.mix_isDist
#print axioms CK.marg_noisy_mul_lam
#print axioms CK.condDist_noisy
#print axioms CK.sum_marg_noisy_lam
#print axioms CK.onebit_step
#print axioms CK.deficit_mix_le
#print axioms CK.deficit_noisy_le_aux
#print axioms CK.deficit_noisy_le
#print axioms CK.Cube
#print axioms CK.BooleanFunction
#print axioms CK.indicator
#print axioms CK.sign
#print axioms CK.avg
#print axioms CK.kernel
#print axioms CK.binaryEntropy
#print axioms CK.eta
#print axioms CK.kappa
#print axioms CK.mean
#print axioms CK.posterior
#print axioms CK.conditionalEntropy
#print axioms CK.information
#print axioms CK.varianceProfile
#print axioms CK.mixedEntropy
#print axioms CK.scalarSlack
#print axioms CK.CourtadeKumar
#print axioms CK.ScalarMixingClaim
#print axioms CK.LinearScalarMixingClaim
#print axioms CK.LowNoiseProfileClaim
#print axioms CK.lowNoiseCK
#print axioms CK.complementaryCK
#print axioms CK.assemble_conditional
#print axioms CK.indicator_square
#print axioms CK.sign_square
#print axioms CK.entropy_zero
#print axioms CK.entropy_one
#print axioms CK.eta_eq_binaryEntropy_eps
#print axioms CK.log_inv_ge
#print axioms CK.binaryEntropy_mono_half
#print axioms CK.le_binaryEntropy_of_small
#print axioms CK.binaryEntropy_ge_eps
#print axioms CK.K0_ge_alpha
#print axioms CK.J0_ge_rbeta
#print axioms CK.M0_ge
#print axioms CK.ell_le
#print axioms CK.q0_ge_Q
#print axioms CK.alpha_ge
#print axioms CK.gfun
#print axioms CK.hasDerivAt_gfun
#print axioms CK.gfun_deriv_nonneg
#print axioms CK.gfun_monotone
#print axioms CK.gfun_one_nonneg
#print axioms CK.gfun_exp_nonneg
#print axioms CK.core_psi
#print axioms CK.endpoint_assemble
#print axioms CK.endpoint_normalized
#print axioms CK.log_inv_eps_eq
#print axioms CK.neg_mul_log_le
#print axioms CK.log_one_add_two_mul_le_tangent
#print axioms CK.one_le_neg_log_of_le_third
#print axioms CK.Q_ge_bound
#print axioms CK.endpoint_interval
#print axioms CK.gain_dominance
#print axioms CK.log_five_le_two
#print axioms CK.log_twenty_le
#print axioms CK.binaryEntropy_le_half_of_small
#print axioms CK.lowNoiseCK_of_profile
#print axioms CK.lowNoiseCK_of_scalar_and_pinsker
#print axioms CK.atanhLog_zero
#print axioms CK.atanhLog_neg
#print axioms CK.curvature_even
#print axioms CK.eta_even
#print axioms CK.eta_zero
#print axioms CK.eta_one
#print axioms CK.kappa_zero
#print axioms CK.atanhLog_nonneg
#print axioms CK.atanhLog_mono
#print axioms CK.le_atanhLog
#print axioms CK.eta_nonneg
#print axioms CK.eta_pos
#print axioms CK.curvature_pos
#print axioms CK.one_le_curvature
#print axioms CK.curvature_mono
#print axioms CK.continuous_binaryEntropy
#print axioms CK.continuous_eta
#print axioms CK.hasDerivAt_binaryEntropy
#print axioms CK.hasDerivAt_eta
#print axioms CK.hasDerivAt_atanhLog
#print axioms CK.eta_antitoneOn
#print axioms CK.eta_le_eta
#print axioms CK.eta_le_log_two
#print axioms CK.kappa_ge_half_sq
#print axioms CK.hasDerivAt_curvature
#print axioms CK.chi
#print axioms CK.fourierCoeff
#print axioms CK.weight
#print axioms CK.signOf
#print axioms CK.negCube
#print axioms CK.sign_mul_self
#print axioms CK.sign_mul_sign
#print axioms CK.sign_not
#print axioms CK.avg_const
#print axioms CK.avg_neg
#print axioms CK.sum_div_const
#print axioms CK.avg_finset_sum
#print axioms CK.chi_empty
#print axioms CK.chi_singleton
#print axioms CK.chi_eq_prod_univ
#print axioms CK.chi_mul_self
#print axioms CK.chi_mul
#print axioms CK.avg_chi
#print axioms CK.chi_orthonormal
#print axioms CK.sum_chi_mul_chi
#print axioms CK.fourier_expansion
#print axioms CK.plancherel
#print axioms CK.parseval
#print axioms CK.weight_nonneg
#print axioms CK.sum_weight
#print axioms CK.fourierCoeff_empty
#print axioms CK.weight_zero
#print axioms CK.weight_one
#print axioms CK.fourierCoeff_add
#print axioms CK.fourierCoeff_const_mul
#print axioms CK.fourierCoeff_const
#print axioms CK.signOf_sq
#print axioms CK.signOf_eq
#print axioms CK.avg_signOf
#print axioms CK.abs_signOf
#print axioms CK.fourierCoeff_indicator
#print axioms CK.negCube_negCube
#print axioms CK.negCubeEquiv
#print axioms CK.chi_negCube
#print axioms CK.avg_comp_negCube
#print axioms CK.fourierCoeff_comp_negCube
#print axioms CK.fourierCoeff_singleton_last
#print axioms CK.chi_map_castSucc
#print axioms CK.fourierCoeff_castSucc_image
#print axioms CK.fourierCoeff_comp_perm_singleton
#print axioms CK.weight_one_comp_perm
#print axioms CK.weight_one_le_avg_sq
#print axioms CK.fourierCoeff_oddPart_singleton
#print axioms CK.indicator_mul_ge
#print axioms CK.weight_one_indicator_le
#print axioms CK.avg_mul_signSum
#print axioms CK.mul_le_half_add_abs
#print axioms CK.weight_one_le_of_small_coeffs
#print axioms CK.map_castSuccEmb_singleton
#print axioms CK.fourierCoeff_castSucc_singleton
#print axioms CK.weight_one_snoc_le
#print axioms CK.weight_one_le_of_large_last
#print axioms CK.balanced_first_level
#print axioms CK.lift
#print axioms CK.decide_eq_true_fun
#print axioms CK.decide_eq_false_fun
#print axioms CK.lift_snoc_true
#print axioms CK.lift_snoc_false
#print axioms CK.signOf_lift_true
#print axioms CK.signOf_lift_false
#print axioms CK.avg_signOf_lift
#print axioms CK.fourierCoeff_lift_last
#print axioms CK.fourierCoeff_lift_castSucc
#print axioms CK.weight_one_lift
#print axioms CK.bias_inclusive_cap
#print axioms CK.atanhLog_le_mul_curvature
#print axioms CK.atanhLog_div_le
#print axioms CK.gain_integral
#print axioms CK.neg_log_one_sub_ge
#print axioms CK.neg_log_one_sub_le
#print axioms CK.neg_log_one_sub_ge'
#print axioms CK.binaryEntropy_le_mul
#print axioms CK.abstract_profile_induction
#print axioms CK.infoP
#print axioms CK.card_cube_real
#print axioms CK.sum_one_cube
#print axioms CK.avg_const'
#print axioms CK.avg_lin2
#print axioms CK.avg_noisy
#print axioms CK.noisy_const
#print axioms CK.noisy_lin
#print axioms CK.noisy_smul_one_sub
#print axioms CK.ent_smul
#print axioms CK.sum_binaryEntropy_eq_ent
#print axioms CK.infoP_const
#print axioms CK.infoP_eq_deficit
#print axioms CK.infoP_noisy_le
#print axioms CK.posterior_eq_noisy
#print axioms CK.infoP_posterior
#print axioms CK.binaryEntropy_indicator
#print axioms CK.infoP_indicator
#print axioms CK.information_le_contraction
#print axioms CK.kernel_compose
#print axioms CK.noisy_noisy
#print axioms CK.information_degrade
#print axioms CK.binaryEntropy_mix_indicator
#print axioms CK.conditionalEntropy_ge_conditional
#print axioms CK.cInt
#print axioms CK.cInt_nonneg
#print axioms CK.cInt_mono
#print axioms CK.cInt_ge_lin
#print axioms CK.cInt_div_mono
#print axioms CK.cInt_eq_log
#print axioms CK.cInt_half
#print axioms CK.cInt_3_4
#print axioms CK.cInt_4_5
#print axioms CK.cInt_21_25
#print axioms CK.cInt_22_25
#print axioms CK.eta_half
#print axioms CK.eta_3_4
#print axioms CK.eta_4_5
#print axioms CK.eta_21_25
#print axioms CK.eta_22_25
#print axioms CK.table_bound
#print axioms CK.hasDerivAt_psiInt
#print axioms CK.psi_mono
#print axioms CK.interior_product
#print axioms CK.kappa_even
#print axioms CK.kappa_one
#print axioms CK.kappa_nonneg
#print axioms CK.continuous_kappa
#print axioms CK.kappa_closed
#print axioms CK.hasSum_kappa
#print axioms CK.kappa_ge_partial
#print axioms CK.kappa_scaling_of_abs_lt
#print axioms CK.kappa_scaling
#print axioms CK.eta_one_sub_two_mul
#print axioms CK.binaryEntropy_mean_le_half
#print axioms CK.large_bias
#print axioms CK.concaveOn_eta
#print axioms CK.kappa_comb_term_nonneg
#print axioms CK.kappa_comb_partial_bound
#print axioms CK.large_coord_scalar_endpoint
#print axioms CK.large_coord_scalar
#print axioms CK.pairEntropy_neg_left
#print axioms CK.hasDerivAt_Lpair_nu
#print axioms CK.D0
#print axioms CK.D0_abs
#print axioms CK.D0_eq
#print axioms CK.D0_nonneg
#print axioms CK.curvature_comb_eq
#print axioms CK.U_le_U_zero
#print axioms CK.indicator_not
#print axioms CK.mean_compl
#print axioms CK.posterior_compl
#print axioms CK.information_compl
#print axioms CK.sigma_ge
#print axioms CK.large_coord_assemble
#print axioms CK.binaryEntropy_eq_eta_rho
#print axioms CK.large_coordinate_last_of_nonneg
#print axioms CK.large_coordinate_last
#print axioms CK.logEnclosure_proved
#print axioms CK.binaryEntropy_eq_eta_rho'
#print axioms CK.avg_signOf_mem_of_cap
#print axioms CK.abs_noiseOp_signOf_le_one
#print axioms CK.gamma_le_lambdaDenom
#print axioms CK.eta_lt_of_ge_three_fifths
#print axioms CK.middle_core
#print axioms CK.middle_range
#print axioms CK.high_core
#print axioms CK.information_anchor_le
#print axioms CK.high_noise
#print axioms CK.noiseOp
#print axioms CK.kernel_factor_sign
#print axioms CK.noiseOp_chi
#print axioms CK.noiseOp_add
#print axioms CK.noiseOp_const_mul
#print axioms CK.noiseOp_eq_sum
#print axioms CK.fourierCoeff_noiseOp
#print axioms CK.posterior_eq_noiseOp
#print axioms CK.abs_noiseOp_le_one
#print axioms CK.binaryEntropy_mean_eq
#print axioms CK.conditionalEntropy_eq_avg_eta
#print axioms CK.conditionalEntropy_eq_avg_eta_abs
#print axioms CK.cancellation
#print axioms CK.cancel_term_nonpos
#print axioms CK.cancel_sum_le
#print axioms CK.energy_lower_bound
#print axioms CK.binaryEntropy_eq_binEntropy
#print axioms CK.two_mul_le_log_sub_log
#print axioms CK.binEntropy_half
#print axioms CK.hasDerivAt_F
#print axioms CK.pinsker_upper
#print axioms CK.pinsker
#print axioms CK.lowNoiseCK_of_scalar
#print axioms CK.Lpair
#print axioms CK.eta_abs
#print axioms CK.curvature_abs
#print axioms CK.atanhLog_sq_abs
#print axioms CK.pairEntropy_zero_left
#print axioms CK.pairEntropy_nonneg
#print axioms CK.pairEntropy_pos
#print axioms CK.Lpair_nonneg
#print axioms CK.continuous_pairEntropy_nu
#print axioms CK.hasDerivAt_pairEntropy_nu
#print axioms CK.hasDerivAt_pairEntropy_z
#print axioms CK.hasDerivAt_Lpair_z
#print axioms CK.Lpair_le
#print axioms CK.pairEntropy_mul_Lpair_le
#print axioms CK.product_centering
#print axioms CK.avg_linear3
#print axioms CK.profile_zero
#print axioms CK.binaryEntropy_one
#print axioms CK.binaryEntropy_zero
#print axioms CK.profile_one
#print axioms CK.profile_step_of_scalar
#print axioms CK.lowNoiseProfile_of_scalar
#print axioms CK.relabel
#print axioms CK.permCube
#print axioms CK.permCube_apply
#print axioms CK.sum_cube_comp
#print axioms CK.kernel_comp
#print axioms CK.posterior_relabel
#print axioms CK.avg_comp
#print axioms CK.mean_relabel
#print axioms CK.conditionalEntropy_relabel
#print axioms CK.information_relabel
#print axioms CK.mixing_interior
#print axioms CK.mixing_endpoint_small
#print axioms CK.mixing_endpoint_large
#print axioms CK.linear_scalar_mixing
#print axioms CK.scalar_mixing
#print axioms CK.lowNoise_proved
#print axioms CK.sectionLast
#print axioms CK.kernel_snoc
#print axioms CK.posterior_snoc
#print axioms CK.avg_snoc
#print axioms CK.mean_snoc
#print axioms CK.conditionalEntropy_snoc
#print axioms CK.bool_sum_kernel_factor
#print axioms CK.kernel_row_sum
#print axioms CK.kernel_symm
#print axioms CK.kernel_nonneg
#print axioms CK.indicator_nonneg
#print axioms CK.indicator_le_one
#print axioms CK.posterior_nonneg
#print axioms CK.posterior_le_one
#print axioms CK.posterior_mean
#print axioms CK.signSum
#print axioms CK.pw
#print axioms CK.mom
#print axioms CK.sign_true
#print axioms CK.sign_false
#print axioms CK.signSum_snoc
#print axioms CK.pw_snoc
#print axioms CK.avg_const_cube
#print axioms CK.avg_sum
#print axioms CK.avg_mul_const
#print axioms CK.mom_snoc
#print axioms CK.Moments
#print axioms CK.moments_zero
#print axioms CK.moments_snoc
#print axioms CK.moments
#print axioms CK.avg_signSum_sq
#print axioms CK.avg_signSum_pow4
#print axioms CK.avg_signSum_pow6
#print axioms CK.avg_signSum_pow8
#print axioms CK.avg_signSum_pow10
#print axioms CK.avg_signSum
#print axioms CK.avg_majorant_signSum
#print axioms CK.pw_nonneg
#print axioms CK.pw_add_two_le
#print axioms CK.capped_poly_bound
#print axioms CK.capped_sign_sum
#print axioms CK.swapLast
#print axioms CK.snoc_snoc_swap
#print axioms CK.sectionLast_relabel_swap
#print axioms CK.mean_nonneg
#print axioms CK.mean_le_one
#print axioms CK.gapLast
#print axioms CK.mean_sectionLast_relabel_swap
#print axioms CK.gap_sum_le_one
#print axioms CK.relabel_one
#print axioms CK.exists_small_gap
#print axioms CK.transfer_product_alg
#print axioms CK.transfer_gain_alg
#print axioms CK.eta_le_log_two'
#print axioms CK.pairEntropy_le_log_two
#print axioms CK.pairEntropy_le_eta
#print axioms CK.transfer_product
#print axioms CK.transfer_gain
#print axioms CK.transfer_relative_alg
#print axioms CK.transfer_relative
#print axioms CKF2.Spec.matches_f1_target
#print axioms CK.courtadeKumar_proved
#print axioms CK.complementary_proved
#print axioms CK.lowNoise_proved
#print axioms CK.scalar_mixing
#print axioms CK.linear_scalar_mixing
